export const mockedProfessionalsServices = [
  {
    id: 209030,
    nome: 'Jackson Amorim da Silva',
    apelido: '00 Jackson',
    servicos: [
      {
        id: 6273462,
        nome: 'COMBO BEMEGASTAR (Senior)',
        descricao: 'COMBO: Reflexo + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 180,
        preco: 569,
        visivelParaCliente: true,
      },
      {
        id: 6273463,
        nome: 'COMBO BEMEGASTYLE (Senior)',
        descricao: 'COMBO: Corte + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 199,
        visivelParaCliente: true,
      },
      {
        id: 7394735,
        nome: 'COMBO BEMEGLAM - (Senior)',
        descricao:
          'Combo: Reflexo + Protetor Plex + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 559.9,
        visivelParaCliente: true,
      },
      {
        id: 6273461,
        nome: 'COMBO BEMEGALISO (Senior)',
        descricao: 'COMBO: Progressiva + Reconstrução \r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 90,
        preco: 320,
        visivelParaCliente: true,
      },
      {
        id: 11868170,
        nome: 'Combo de Corte + Escova',
        descricao: 'Corte + finalização',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 140,
        visivelParaCliente: true,
      },
      {
        id: 11868171,
        nome: 'Combo de Tratamento + Escova',
        descricao: 'Combo de Tratamento com finalização de escova',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 11595106,
        nome: 'Hidratação hit Beauty Combo 4 hidrataçoes c/ escova',
        descricao: '.....',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 520,
        visivelParaCliente: true,
      },
      {
        id: 7772913,
        nome: 'Reflexo (Senior) Longo',
        descricao:
          'Procedimento de descoloração e aplicação de cor parcial por mechas capilares.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 450,
        visivelParaCliente: true,
      },
      {
        id: 5666359,
        nome: 'Corte (Senior)',
        descricao: 'Corte de cabelo feminino, masculino ou infantil.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 15,
        preco: 120,
        visivelParaCliente: true,
      },
      {
        id: 4860821,
        nome: 'Reconstrução The Rescue (Senior)',
        descricao:
          'Tratamento intensivo para reconstrução dos fios danificados e preparação para o processo de reflexo.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 30,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 7772907,
        nome: 'Coloração/Tonalização (Senior) Longo',
        descricao:
          'Procedimento químico ou não químico, para mudança de cor e cobertura de fios brancos\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 290,
        visivelParaCliente: true,
      },
    ],
  },
  {
    id: 284833,
    nome: 'Jardel Xavier de Lima',
    apelido: '00 Dell',
    servicos: [
      {
        id: 6273462,
        nome: 'COMBO BEMEGASTAR (Senior)',
        descricao: 'COMBO: Reflexo + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 180,
        preco: 569,
        visivelParaCliente: true,
      },
      {
        id: 6273463,
        nome: 'COMBO BEMEGASTYLE (Senior)',
        descricao: 'COMBO: Corte + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 199,
        visivelParaCliente: true,
      },
      {
        id: 7394735,
        nome: 'COMBO BEMEGLAM - (Senior)',
        descricao:
          'Combo: Reflexo + Protetor Plex + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 559.9,
        visivelParaCliente: true,
      },
      {
        id: 6273461,
        nome: 'COMBO BEMEGALISO (Senior)',
        descricao: 'COMBO: Progressiva + Reconstrução \r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 90,
        preco: 320,
        visivelParaCliente: true,
      },
      {
        id: 11868170,
        nome: 'Combo de Corte + Escova',
        descricao: 'Corte + finalização',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 140,
        visivelParaCliente: true,
      },
      {
        id: 11868171,
        nome: 'Combo de Tratamento + Escova',
        descricao: 'Combo de Tratamento com finalização de escova',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 11595106,
        nome: 'Hidratação hit Beauty Combo 4 hidrataçoes c/ escova',
        descricao: '.....',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 520,
        visivelParaCliente: true,
      },
      {
        id: 7772913,
        nome: 'Reflexo (Senior) Longo',
        descricao:
          'Procedimento de descoloração e aplicação de cor parcial por mechas capilares.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 450,
        visivelParaCliente: true,
      },
      {
        id: 5666359,
        nome: 'Corte (Senior)',
        descricao: 'Corte de cabelo feminino, masculino ou infantil.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 15,
        preco: 120,
        visivelParaCliente: true,
      },
      {
        id: 4860821,
        nome: 'Reconstrução The Rescue (Senior)',
        descricao:
          'Tratamento intensivo para reconstrução dos fios danificados e preparação para o processo de reflexo.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 30,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 7772907,
        nome: 'Coloração/Tonalização (Senior) Longo',
        descricao:
          'Procedimento químico ou não químico, para mudança de cor e cobertura de fios brancos\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 290,
        visivelParaCliente: true,
      },
      {
        id: 7772909,
        nome: 'Penteado (Senior) Curto',
        descricao: 'Procedimento de pentear e modelar o cabelo.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 200,
        visivelParaCliente: true,
      },
    ],
  },
  {
    id: 618259,
    nome: 'VALDIR FOGAÇA DE OLIVEIRA',
    apelido: '00 Val',
    servicos: [
      {
        id: 6273462,
        nome: 'COMBO BEMEGASTAR (Senior)',
        descricao: 'COMBO: Reflexo + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 180,
        preco: 569,
        visivelParaCliente: true,
      },
      {
        id: 6273463,
        nome: 'COMBO BEMEGASTYLE (Senior)',
        descricao: 'COMBO: Corte + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 199,
        visivelParaCliente: true,
      },
      {
        id: 7394735,
        nome: 'COMBO BEMEGLAM - (Senior)',
        descricao:
          'Combo: Reflexo + Protetor Plex + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 559.9,
        visivelParaCliente: true,
      },
      {
        id: 6273461,
        nome: 'COMBO BEMEGALISO (Senior)',
        descricao: 'COMBO: Progressiva + Reconstrução \r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 90,
        preco: 320,
        visivelParaCliente: true,
      },
      {
        id: 11868170,
        nome: 'Combo de Corte + Escova',
        descricao: 'Corte + finalização',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 140,
        visivelParaCliente: true,
      },
      {
        id: 11868171,
        nome: 'Combo de Tratamento + Escova',
        descricao: 'Combo de Tratamento com finalização de escova',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 11595106,
        nome: 'Hidratação hit Beauty Combo 4 hidrataçoes c/ escova',
        descricao: '.....',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 520,
        visivelParaCliente: true,
      },
      {
        id: 11595108,
        nome: 'Hidratação Hit Beuty Absolut Repair S/ escova',
        descricao: '..',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 20,
        preco: 130,
        visivelParaCliente: true,
      },
      {
        id: 7772913,
        nome: 'Reflexo (Senior) Longo',
        descricao:
          'Procedimento de descoloração e aplicação de cor parcial por mechas capilares.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 450,
        visivelParaCliente: true,
      },
      {
        id: 5666359,
        nome: 'Corte (Senior)',
        descricao: 'Corte de cabelo feminino, masculino ou infantil.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 15,
        preco: 120,
        visivelParaCliente: true,
      },
      {
        id: 4860821,
        nome: 'Reconstrução The Rescue (Senior)',
        descricao:
          'Tratamento intensivo para reconstrução dos fios danificados e preparação para o processo de reflexo.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 30,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 7772907,
        nome: 'Coloração/Tonalização (Senior) Longo',
        descricao:
          'Procedimento químico ou não químico, para mudança de cor e cobertura de fios brancos\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 290,
        visivelParaCliente: true,
      },
    ],
  },
  {
    id: 635516,
    nome: 'Luana Menandro Maximiano',
    apelido: '00 Luana Menandro',
    servicos: [
      {
        id: 6273462,
        nome: 'COMBO BEMEGASTAR (Senior)',
        descricao: 'COMBO: Reflexo + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 180,
        preco: 569,
        visivelParaCliente: true,
      },
      {
        id: 6273463,
        nome: 'COMBO BEMEGASTYLE (Senior)',
        descricao: 'COMBO: Corte + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 199,
        visivelParaCliente: true,
      },
      {
        id: 7394735,
        nome: 'COMBO BEMEGLAM - (Senior)',
        descricao:
          'Combo: Reflexo + Protetor Plex + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 559.9,
        visivelParaCliente: true,
      },
      {
        id: 6273461,
        nome: 'COMBO BEMEGALISO (Senior)',
        descricao: 'COMBO: Progressiva + Reconstrução \r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 90,
        preco: 320,
        visivelParaCliente: true,
      },
      {
        id: 11868170,
        nome: 'Combo de Corte + Escova',
        descricao: 'Corte + finalização',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 140,
        visivelParaCliente: true,
      },
      {
        id: 11868171,
        nome: 'Combo de Tratamento + Escova',
        descricao: 'Combo de Tratamento com finalização de escova',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 11595106,
        nome: 'Hidratação hit Beauty Combo 4 hidrataçoes c/ escova',
        descricao: '.....',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 520,
        visivelParaCliente: true,
      },
      {
        id: 7772913,
        nome: 'Reflexo (Senior) Longo',
        descricao:
          'Procedimento de descoloração e aplicação de cor parcial por mechas capilares.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 450,
        visivelParaCliente: true,
      },
      {
        id: 5666359,
        nome: 'Corte (Senior)',
        descricao: 'Corte de cabelo feminino, masculino ou infantil.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 15,
        preco: 120,
        visivelParaCliente: true,
      },
      {
        id: 4860821,
        nome: 'Reconstrução The Rescue (Senior)',
        descricao:
          'Tratamento intensivo para reconstrução dos fios danificados e preparação para o processo de reflexo.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 30,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 7772907,
        nome: 'Coloração/Tonalização (Senior) Longo',
        descricao:
          'Procedimento químico ou não químico, para mudança de cor e cobertura de fios brancos\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 290,
        visivelParaCliente: true,
      },
      {
        id: 7772890,
        nome: 'Maquiagem III',
        descricao: 'Procedimento de maquiagem',
        categoria: 'Maquiagem',
        duracaoEmMinutos: 60,
        preco: 300,
        visivelParaCliente: true,
      },
    ],
  },
  {
    id: 746338,
    nome: 'EMERSON GOMES DO NASCIMENTO',
    apelido: '00 EMERSON',
    servicos: [
      {
        id: 6273462,
        nome: 'COMBO BEMEGASTAR (Senior)',
        descricao: 'COMBO: Reflexo + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 180,
        preco: 569,
        visivelParaCliente: true,
      },
      {
        id: 6273463,
        nome: 'COMBO BEMEGASTYLE (Senior)',
        descricao: 'COMBO: Corte + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 199,
        visivelParaCliente: true,
      },
      {
        id: 7394735,
        nome: 'COMBO BEMEGLAM - (Senior)',
        descricao:
          'Combo: Reflexo + Protetor Plex + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 559.9,
        visivelParaCliente: true,
      },
      {
        id: 6273461,
        nome: 'COMBO BEMEGALISO (Senior)',
        descricao: 'COMBO: Progressiva + Reconstrução \r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 90,
        preco: 320,
        visivelParaCliente: true,
      },
      {
        id: 11868170,
        nome: 'Combo de Corte + Escova',
        descricao: 'Corte + finalização',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 140,
        visivelParaCliente: true,
      },
      {
        id: 11868171,
        nome: 'Combo de Tratamento + Escova',
        descricao: 'Combo de Tratamento com finalização de escova',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 11595106,
        nome: 'Hidratação hit Beauty Combo 4 hidrataçoes c/ escova',
        descricao: '.....',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 520,
        visivelParaCliente: true,
      },
      {
        id: 11595108,
        nome: 'Hidratação Hit Beuty Absolut Repair S/ escova',
        descricao: '..',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 20,
        preco: 130,
        visivelParaCliente: true,
      },
      {
        id: 7772913,
        nome: 'Reflexo (Senior) Longo',
        descricao:
          'Procedimento de descoloração e aplicação de cor parcial por mechas capilares.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 450,
        visivelParaCliente: true,
      },
      {
        id: 5666359,
        nome: 'Corte (Senior)',
        descricao: 'Corte de cabelo feminino, masculino ou infantil.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 15,
        preco: 120,
        visivelParaCliente: true,
      },
      {
        id: 4860821,
        nome: 'Reconstrução The Rescue (Senior)',
        descricao:
          'Tratamento intensivo para reconstrução dos fios danificados e preparação para o processo de reflexo.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 30,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 7772907,
        nome: 'Coloração/Tonalização (Senior) Longo',
        descricao:
          'Procedimento químico ou não químico, para mudança de cor e cobertura de fios brancos\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 290,
        visivelParaCliente: true,
      },
    ],
  },
  {
    id: 229782,
    nome: 'Yuri Ramos Oliveira',
    apelido: '00 Yuri Ramos',
    servicos: [
      {
        id: 6273462,
        nome: 'COMBO BEMEGASTAR (Senior)',
        descricao: 'COMBO: Reflexo + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 180,
        preco: 569,
        visivelParaCliente: true,
      },
      {
        id: 6273463,
        nome: 'COMBO BEMEGASTYLE (Senior)',
        descricao: 'COMBO: Corte + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 199,
        visivelParaCliente: true,
      },
      {
        id: 7394735,
        nome: 'COMBO BEMEGLAM - (Senior)',
        descricao:
          'Combo: Reflexo + Protetor Plex + Reconstrução + Escova ou Babyliss\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 559.9,
        visivelParaCliente: true,
      },
      {
        id: 6273461,
        nome: 'COMBO BEMEGALISO (Senior)',
        descricao: 'COMBO: Progressiva + Reconstrução \r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 90,
        preco: 320,
        visivelParaCliente: true,
      },
      {
        id: 11868170,
        nome: 'Combo de Corte + Escova',
        descricao: 'Corte + finalização',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 140,
        visivelParaCliente: true,
      },
      {
        id: 11868171,
        nome: 'Combo de Tratamento + Escova',
        descricao: 'Combo de Tratamento com finalização de escova',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 40,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 11595106,
        nome: 'Hidratação hit Beauty Combo 4 hidrataçoes c/ escova',
        descricao: '.....',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 520,
        visivelParaCliente: true,
      },
      {
        id: 11595108,
        nome: 'Hidratação Hit Beuty Absolut Repair S/ escova',
        descricao: '..',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 20,
        preco: 130,
        visivelParaCliente: true,
      },
      {
        id: 7772913,
        nome: 'Reflexo (Senior) Longo',
        descricao:
          'Procedimento de descoloração e aplicação de cor parcial por mechas capilares.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 120,
        preco: 450,
        visivelParaCliente: true,
      },
      {
        id: 5666359,
        nome: 'Corte (Senior)',
        descricao: 'Corte de cabelo feminino, masculino ou infantil.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 15,
        preco: 120,
        visivelParaCliente: true,
      },
      {
        id: 4860821,
        nome: 'Reconstrução The Rescue (Senior)',
        descricao:
          'Tratamento intensivo para reconstrução dos fios danificados e preparação para o processo de reflexo.',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 30,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 7772907,
        nome: 'Coloração/Tonalização (Senior) Longo',
        descricao:
          'Procedimento químico ou não químico, para mudança de cor e cobertura de fios brancos\r\n',
        categoria: 'Profissional Sozinho',
        duracaoEmMinutos: 60,
        preco: 290,
        visivelParaCliente: true,
      },
    ],
  },
  {
    id: 505936,
    nome: 'Jane Alves Siqueira',
    apelido: '01 Jane',
    servicos: [
      {
        id: 4858026,
        nome: 'MANICURE E PEDICURE',
        descricao: 'Procedimento de mudança e cor das unhas',
        categoria: 'Manicure',
        duracaoEmMinutos: 90,
        preco: 85,
        visivelParaCliente: true,
      },
      {
        id: 13038118,
        nome: 'Manicure e Pedicure (IA)',
        descricao: 'Manicure e Pedicure Tradicional',
        categoria: 'IA',
        duracaoEmMinutos: 120,
        preco: 85,
        visivelParaCliente: true,
      },
      {
        id: 8750205,
        nome: 'Pedicure (App)',
        descricao: 'Higiene, cuticulagem e esmaltação das unhas dos pés.',
        categoria: 'Manicure',
        duracaoEmMinutos: 30,
        preco: 45,
        visivelParaCliente: true,
      },
      {
        id: 11595114,
        nome: 'Pedicure Eurofarama Francesinha',
        descricao: 'Eurofaram',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 35,
        visivelParaCliente: true,
      },
      {
        id: 8750196,
        nome: 'Coloração de Sobrancelha (App)',
        descricao: 'Pigmentação das sobrancelhas, feita com tonalizante.',
        categoria: 'Sobrancelha',
        duracaoEmMinutos: 40,
        preco: 55,
        visivelParaCliente: true,
      },
      {
        id: 8750200,
        nome: 'Design de Sobrancelha(App)',
        descricao: 'Desenho criado sob medida para realçar o olhar.',
        categoria: 'Sobrancelha',
        duracaoEmMinutos: 40,
        preco: 45,
        visivelParaCliente: true,
      },
      {
        id: 8750203,
        nome: 'Limpeza de Sobrancelha.(App)',
        descricao:
          'Remove os pêlos da sobrancelha e promove a harmonia do olhar.',
        categoria: 'Sobrancelha',
        duracaoEmMinutos: 30,
        preco: 35,
        visivelParaCliente: true,
      },
      {
        id: 8750199,
        nome: 'Depilação (App)',
        descricao: 'Remoção de pêlos da face ou corpo.',
        categoria: 'Depilação',
        duracaoEmMinutos: 30,
        preco: 50,
        visivelParaCliente: true,
      },
      {
        id: 11577714,
        nome: 'Depilação Buço - com cera/ Nariz - Hit Beauty',
        descricao: '...',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 15,
        preco: 20,
        visivelParaCliente: true,
      },
      {
        id: 11595102,
        nome: 'Depilação hit Beauty Virilha completa s/intima',
        descricao: '.....',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 70,
        visivelParaCliente: true,
      },
      {
        id: 12763028,
        nome: 'DEPILACAO MASC. COM CERA SOBRANCELHA',
        descricao: '..',
        categoria: 'Depilação',
        duracaoEmMinutos: 40,
        preco: 65,
        visivelParaCliente: true,
      },
      {
        id: 12763030,
        nome: 'DEPILACAO MASC. COM INTIMA',
        descricao: '..',
        categoria: 'Depilação',
        duracaoEmMinutos: 40,
        preco: 150,
        visivelParaCliente: true,
      },
      {
        id: 11577726,
        nome: 'Depilação Virilha Cavada - Hit Beauty',
        descricao: '...',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 30,
        preco: 65,
        visivelParaCliente: true,
      },
    ],
  },
  {
    id: 657506,
    nome: 'Cristiana do Santos Nobre',
    apelido: '01 Cristiana',
    servicos: [
      {
        id: 4858026,
        nome: 'MANICURE E PEDICURE',
        descricao: 'Procedimento de mudança e cor das unhas',
        categoria: 'Manicure',
        duracaoEmMinutos: 90,
        preco: 85,
        visivelParaCliente: true,
      },
      {
        id: 13038118,
        nome: 'Manicure e Pedicure (IA)',
        descricao: 'Manicure e Pedicure Tradicional',
        categoria: 'IA',
        duracaoEmMinutos: 120,
        preco: 85,
        visivelParaCliente: true,
      },
      {
        id: 8750205,
        nome: 'Pedicure (App)',
        descricao: 'Higiene, cuticulagem e esmaltação das unhas dos pés.',
        categoria: 'Manicure',
        duracaoEmMinutos: 30,
        preco: 45,
        visivelParaCliente: true,
      },
      {
        id: 11595114,
        nome: 'Pedicure Eurofarama Francesinha',
        descricao: 'Eurofaram',
        categoria: 'Hit Beauty/Eurofarma',
        duracaoEmMinutos: 40,
        preco: 35,
        visivelParaCliente: true,
      },
    ],
  },
];
